config/routes.rb
Rails.application.routes.draw do
  root to: 'star_wars#categories'
  get 'load_next_items', to: "star_wars#load_next_items", as: :load_next_items
  get 'historics', to: 'star_wars#historics', as: :historics
  get ':category', to: "star_wars#category_items", as: :category
  get ':category/:id', to: "star_wars#item", as: :category_item
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/historic.rb
class Historic < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:collection, :item]
  def index
  end

  def collection
    @datas = SwapiService.new(category: @category).get
    @category_icon = @datas['results'].nil? ? 'question-circle' : SwapiService::CATEGORIES[@category][:font_awesome_icon]
  end

  def item
    @id = params[:id]
    @datas = SwapiService.new(category: @category, id: @id).get
    Historic.create(name: @datas['name'] || @datas['title'], category: @category, item_id: @id)
  end

  def load_next_items
    @datas = SwapiService.new(url: params[:url]).get
    @category = StarWarsHelper.item_category_from_url(params[:url])
    respond_to do |format|
      format.js {render layout: false}
      format.html
    end
  end

  def historics
    @historics = Historic.all.order(created_at: :desc)
  end

  private

  def set_category
    @category = params[:category]
  end
end

app/controllers/star_wars_controller.rb
class StarWarsController < ApplicationController
  before_action :set_category, only: [:category_items, :item]
  def categories
  end

  def category_items
    @datas = SwapiService.new(category: @category).get
    @category_icon = @datas['results'].nil? ? 'question-circle' : SwapiService::CATEGORIES[@category][:font_awesome_icon]
  end

  def item
    @id = params[:id]
    @datas = SwapiService.new(category: @category, id: @id).get
    Historic.create(name: @datas['name'] || @datas['title'], category: @category, item_id: @id)
  end

  def load_next_items
    @datas = SwapiService.new(url: params[:url]).get
    @category = StarWarsHelper.item_category_from_url(params[:url])
    respond_to do |format|
      format.js {render layout: false}
      format.html
    end
  end

  def historics
    @historics = Historic.all.order(created_at: :desc)
  end

  private

  def set_category
    @category = params[:category]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/star_wars_helper.rb
require 'font-awesome-sass'

module StarWarsHelper

  def self.item_id_from_url(item_url)
    item_url.match(/\/(?<id>\d{1,3})\/$/)['id'].to_i
  end

  def self.item_category_from_url(url)
    url.match(/^https\:\/\/swapi\.dev\/api\/(?<category>\w+)/)['category']
  end

  def self.font_awesome_icon_from_category(category)
    icon_name = SwapiService::CATEGORIES[category][:font_awesome_icon]
    icon('fas', icon_name)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SwapiViewer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div id="navbar">
  <h1>SWAPI VIEWER</h1>
  <div id="menu">
    <div id="categories">
      <% SwapiService::CATEGORIES.each do |category, data| %>
        <%= link_to category_path(category) do %>
          <%= icon('fas', SwapiService::CATEGORIES[category][:font_awesome_icon]) %> <%= category %>
        <% end %>
      <% end %>
    </div>
    <%= link_to "Historics", historics_path %>
  </div>  
  <hr>
</div>

app/views/star_wars/_item_card.html.erb
<%= link_to category_item_path(category, StarWarsHelper::item_id_from_url(item['url'])), class: 'card-item' do %>
  <%= item['name'] || item['title'] %>
<% end %>

app/views/star_wars/_item_display.html.erb
<div class="sub-elements">
    <div class= "designation"><%= item_cat.capitalize %></div>
    <div class="list">
      <% items.each do |item_url| %>
        <%= link_to category_item_path(StarWarsHelper::item_category_from_url(item_url), StarWarsHelper::item_id_from_url(item_url)), class: "#{item_cat} item" do %>
          <%= icon('fas', SwapiService::CATEGORIES[StarWarsHelper::item_category_from_url(item_url)][:font_awesome_icon]) %>
          <span><%= item_url %></span>
        <% end %>
        <hr>
      <% end %>
    </div>
  </div>

app/views/star_wars/categories.html.erb
<h1>Star Wars Categories</h1>

<div class="cards-category">
  <% SwapiService::CATEGORIES.each do |category, data| %>
    <%= link_to category_path(category), class: "card-category" do %>
      <%= icon('fas', data[:font_awesome_icon]) %>
      <span><%= category.capitalize %></span>
    <% end %>
  <% end %>
</div>

app/views/star_wars/category_items.html.erb
<h1><%= icon('fas', @category_icon) %> <%= @category.capitalize %></h1>

<div><%= @datas[:message] %></div>

<div class="cards-item">
  <% @datas['results']&.each do |item| %>
    <%= render 'item_card', item: item, category: @category %>
  <% end %>
</div>
<hr>
<% if @datas['next'] %>
  <%= link_to load_next_items_path(url: @datas['next']), remote: true, id: "load-next-items" do %>
    <div class="">Load more...</div>
  <% end %>
<% end %>
<hr>

app/views/star_wars/historics.html.erb
<h1>Historics</h1>
<div class="historics">
  <% @historics.each do |historic| %>
    <div class="historic">
      <%= link_to category_item_path(historic.category, historic.item_id) do %>
        <%= icon('fas', SwapiService::CATEGORIES[historic.category][:font_awesome_icon]) %> <%= historic['name'] %>
      <% end %>
      <div id="historic-time"><%= (historic.created_at + Time.now.utc_offset).utc.strftime("%d/%m/%Y at %H:%M:%S") %></div>
    </div>
  <% end %>
</div>

app/views/star_wars/item.html.erb
<h1><%= @datas['name'] || @datas['title'] %></h1>

<% if @datas['homeworld'] %>
  <%= render 'item_display', items: [@datas['homeworld']], item_cat: 'homeworld' %>
<% end %>

<% %w[pilots characters residents people planets starships vehicles species films].each do |item_cat| %>
  <% if @datas[item_cat] %>
    <%= render 'item_display', items: @datas[item_cat], item_cat: item_cat %>
  <% end %>
<% end %>

app/views/star_wars/load_next_items.js.erb
console.log("Next: "+ "<%= @datas['next'] %>");

<% @datas['results'].each do |item| %>
  document.querySelector('div.cards-item').innerHTML += "<%= escape_javascript(render partial: 'item_card', locals: { item: item, category: @category } ) %>";
<% end %>

<% if @datas['next'] %>
  document.querySelector('a#load-next-items').href = "/load_next_items?url=" + "<%= escape_javascript(@datas['next']) %>";
<% else %>
  document.querySelector('a#load-next-items').href = "#";
  document.querySelector('a#load-next-items div').innerText = "Full loaded !";
<% end %>